language: java

sudo: required
dist: precise

services:
  - mysql

jdk:
  - oraclejdk8

before_install:
  - chmod a+x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - git add -f gradle/wrapper/gradle-wrapper.jar
  - mysql -e 'CREATE DATABASE jiriki_db_test;'
  - mysql -e 'CREATE USER "jiriki" identified by "jiriki"'
  - sudo mysql -e 'GRANT ALL ON jiriki_db_test.* TO jiriki'

after_success:
  - ./gradlew test jacocoTestReport coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew dockerPushImage -Pdockerusername=$DOCKER_USERNAME -Pdockerpassword=$DOCKER_PASSWORD -Pjasypt=$JASYPT_PASSWORD -Pver=$TRAVIS_TAG
  on:
    tags: true
    branch: release
