language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk8

before_install:
  - chmod a+x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - git add -f gradle/wrapper/gradle-wrapper.jar

after_success:
  - ./gradlew test jacocoTestReport coveralls -Pdocker_username=$DOCKER_USERNAME -Pdocker_password=$DOCKER_PASSWORD -Pjasypt.encryptor.password=$JASYPT_PASSWORD

deploy:
  provider: script
  script: ./gradlew pushImage -Pdocker_username=$DOCKER_USERNAME -Pdocker_password=$DOCKER_PASSWORD -Pjasypt.encryptor.password=$JASYPT_PASSWORD
