language: java

sudo: required
dist: trusty

jdk: 
  - oraclejdk8
  
before_install:
  - chmod a+x gradlew && ./gradlew.build
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - git add -f gradle/wrapper/gradle-wrapper.jar