language: java

sudo: required
dist: trusty

services:
  - mysql

jdk:
  - oraclejdk8

before_install:
  - chmod a+x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - git add -f gradle/wrapper/gradle-wrapper.jar
  - sudo cat $TRAVIS_BUILD_DIR/_travis/my.cnf | tee -a ~/.my.cnf
  - cat ~/.my.cnf
  - mysql -e 'SET character_set_server=utf8mb4;'
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE jiriki_db_test CHARACTER SET utf8mb4;'
  - mysql -e 'USE jiriki_db_test;SHOW VARIABLES LIKE "chara%"'

after_success:
  - ./gradlew test jacocoTestReport coveralls

after_failure:
  - mysql -e 'SHOW ENGINE INNODB STATUS;'

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew dockerPushImage -Pdockerusername=$DOCKER_USERNAME -Pdockerpassword=$DOCKER_PASSWORD -Pjasypt=$JASYPT_PASSWORD -Pver=$TRAVIS_TAG
  on:
    tags: true
    branch: release
