language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - chmod a+x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - git add -f gradle/wrapper/gradle-wrapper.jar
  - mysql -e 'CREATE DATABASE jiriki_db_test DEFAULT CHARACTER SET utf8mb4;'

after_success:
  - ./gradlew test jacocoTestReport coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew dockerPushImage -Pdockerusername=$DOCKER_USERNAME -Pdockerpassword=$DOCKER_PASSWORD -Pjasypt=$JASYPT_PASSWORD -Pver=$TRAVIS_TAG
  on:
    tags: true
    branch: release
