language: java

sudo: required
dist: trusty

services:
  - mysql

jdk:
  - oraclejdk8

before_install:
  - chmod a+x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - git add -f gradle/wrapper/gradle-wrapper.jar
  - mysql -e 'CREATE DATABASE jiriki_db;'
  - mysql -e 'CREATE USER "jiriki" identified by "jiriki"'
  - sudo mysql -e 'GRANT ALL ON jiriki_db.* TO jiriki'
  - sudo cat /etc/mysql/my.cnf
  - sudo cat $TRAVIS_BUILD_DIR/_travis/my.cnf  | sudo tee -a /etc/mysql/my.cnf
  - sudo cat /etc/mysql/my.cnf
  - sudo service mysql restart
  - mysql -e 'USE jiriki_db; SHOW VARIABLES LIKE "chara%"'

after_success:
  - ./gradlew test jacocoTestReport coveralls

after_failure:
  - mysql -e 'SHOW ENGINE INNODB STATUS;'

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew dockerPushImage -Pdockerusername=$DOCKER_USERNAME -Pdockerpassword=$DOCKER_PASSWORD -Pjasypt=$JASYPT_PASSWORD -Pver=$TRAVIS_TAG
  on:
    tags: true
    branch: release
