spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiriki_db?serverTimezone=JST&lower_case_table_names=1
    username: mysql
    password: mysql

mybatis:
  configuration:
    map-underscore-to-camel-case: true
      
security:
  oauth2:
    resource:
      id: https://bbp10-jiriki.auth0.com/api/v2/
      jwk:
        key-set-uri: https://bbp10-jiriki.auth0.com/.well-known/jwks.json

google:
  sheet:
    id: 1YBCP7kBrhCha5v8RRklTwXs0rbS437EG1yLNdwFm634
    name: 2. 得点表
    
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug

cors:
  origin: http://localhost:3000