spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://160.16.80.177:3306/jiriki
    username: jiriki
    password: ENC@[ViRdSeAso02m4+wk9vE7izIk7CWNAk/KmJmHrdZyPFI=]
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update

google:
  sheet:
    id: 1YBCP7kBrhCha5v8RRklTwXs0rbS437EG1yLNdwFm634
    name: 2. 得点表

jasypt:
  encryptor:
    property:
      prefix: "ENC@["
      suffix: "]"

auth0:
  audience: https://bbp10-jiriki.auth0.com/api/v2/
  issuer: https://bbp10-jiriki.auth0.com/

cors:
  origin: https://bbp10-jiriki.cf