spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://160.16.80.177:3306/jiriki
    username: jiriki
    password: ENC@[ViRdSeAso02m4+wk9vE7izIk7CWNAk/KmJmHrdZyPFI=]
  jpa:
    hibernate:
      ddl-auto: update

google:
  sheet:
    id: 1YBCP7kBrhCha5v8RRklTwXs0rbS437EG1yLNdwFm634
    name: 2. 得点表

jasypt:
  encryptor:
    property:
      prefix: "ENC@["
      suffix: "]"