spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://160.16.80.177:3306/jiriki
    username: jiriki
    password: ENC@[ViRdSeAso02m4+wk9vE7izIk7CWNAk/KmJmHrdZyPFI=]
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: jiriki_rabbit
    password: ENC@[TeFG0rp0t1irX+fnG8+WmmCLQDmSqdIdPzN1hIQd0pnZjZf6vcp1fw==]

mybatis:
  configuration:
    map-underscore-to-camel-case: true

google:
  sheet:
    id: 1YBCP7kBrhCha5v8RRklTwXs0rbS437EG1yLNdwFm634
    name: 2. 得点表

jasypt:
  encryptor:
    property:
      prefix: "ENC@["
      suffix: "]"

security:
  oauth2:
    resource:
      id: https://bbp10-jiriki.auth0.com/api/v2/
      jwk:
        key-set-uri: https://bbp10-jiriki.auth0.com/.well-known/jwks.json

cors:
  origin: https://bbp10-jiriki.cf