spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiriki_db?serverTimezone=JST
    username: mysql
    password: mysql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: io.github.gogotea55t.jiriki.domain.vo
      
security:
  oauth2:
    resource:
      id: https://bbp10-jiriki.auth0.com/api/v2/
      jwk:
        key-set-uri: https://bbp10-jiriki.auth0.com/.well-known/jwks.json

google:
  sheet:
    id: 1hC3kvvKKZItaKX2yu1Kd7xqpoFgHcu6ri5nk7c6ZTuc
    name: 2. 得点表
    
logging:
  level:
    org.springframework.security: debug
    io.github.gogotea55t.jiriki: debug

cors:
  origin: http://localhost:3000