ALTER TABLE SONGS ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SONGS ADD COLUMN CREATED_BY VARCHAR(30) DEFAULT 'ANONYMOUS';
ALTER TABLE SONGS ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE SONGS ADD COLUMN UPDATED_BY VARCHAR(30) DEFAULT 'ANONYMOUS';

ALTER TABLE SCORES ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SCORES ADD COLUMN CREATED_BY VARCHAR(30) DEFAULT 'ANONYMOUS';
ALTER TABLE SCORES ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE SCORES ADD COLUMN UPDATED_BY VARCHAR(30) DEFAULT 'ANONYMOUS';

ALTER TABLE USERS ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE USERS ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE TWITTER_USERS ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE TWITTER_USERS ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
