CREATE TABLE IF NOT EXISTS WEEKLY_CHALLANGE (
	WEEKLY_CHALLANGE_ID INT PRIMARY KEY AUTO_INCREMENT,
	SONGS_SONG_ID VARCHAR(10) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	FOREIGN KEY (SONGS_SONG_ID) references SONGS(SONG_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE WC_START_DATE_INDEX (START_DATE)
	UNIQUE WC_END_DATE_INDEX (END_DATE)
)/*! CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;